Repository LondonSquad/Tudee, pull requests merged in 2025-06, with the labels that each got.

#96 refactor: fix padding in bottom sheet components
  app/src/main/java/com/london/tudee/presentation/MainActivity.kt
  app/src/main/java/com/london/tudee/presentation/components/bottom_sheet/TudeeBottomSheet.kt
  app/src/main/java/com/london/tudee/presentation/components/bottom_sheet/TudeeBottomSheetScreen.kt
Labels: enhancement

#134 refactor/bottom-sheet-category-interactions
  app/src/main/java/com/london/tudee/presentation/MainActivity.kt
  app/src/main/java/com/london/tudee/presentation/components/CategoryItem.kt
  app/src/main/java/com/london/tudee/presentation/components/bottom_sheet/TudeeBottomSheetScreen.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/CategoriesScreen.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsScreen.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/create_category/CreateCategoryBottomSheet.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/create_category/CreateCategoryViewModel.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/delete_category/DeleteCategoryBottomSheet.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/edit_category/EditCategoryBottomSheet.kt
  app/src/main/java/com/london/tudee/presentation/utils/saveImageToInternalStorage.kt
Labels: bug

#138 feat: Toggle task bottom sheet visibility
  app/src/main/java/com/london/tudee/presentation/screens/home/HomeInteractions.kt
  app/src/main/java/com/london/tudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/london/tudee/presentation/screens/home/HomeViewModel.kt
Labels: bug

#139 fix/add-update-task-bottom-sheet
  app/src/main/java/com/london/tudee/presentation/components/CategoryItem.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsScreen.kt
  app/src/main/java/com/london/tudee/presentation/screens/category/category_details/CategoryDetailsViewModel.kt
  app/src/main/java/com/london/tudee/presentation/screens/home/HomeViewModel.kt
Labels: bug

#141 refactor/on-boarding-screen add navigate on HorizontalPager
  app/src/main/java/com/london/tudee/presentation/components/buttons/TudeeTextButton.kt
  app/src/main/java/com/london/tudee/presentation/screens/onboarding/OnBoardingBackground.kt
  app/src/main/java/com/london/tudee/presentation/screens/onboarding/OnBoardingHorizontalPager.kt
  app/src/main/java/com/london/tudee/presentation/screens/onboarding/OnboardingIndicatorBar.kt
  app/src/main/java/com/london/tudee/presentation/screens/onboarding/OnboardingPages.kt
  app/src/main/java/com/london/tudee/presentation/screens/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/london/tudee/presentation/screens/task/TasksScreen.kt
  app/src/main/res/drawable/vector10.png
  app/src/main/res/drawable/vector10_dark.png
  app/src/main/res/drawable/vector7.png
  app/src/main/res/drawable/vector7_dark.png
  app/src/main/res/drawable/vector9.png
  app/src/main/res/drawable/vector9_dark.png
  app/src/main/res/drawable/vector_10.xml
  app/src/main/res/drawable/vector_10dark.xml
  app/src/main/res/drawable/vector_7.xml
  app/src/main/res/drawable/vector_7dark.xml
  app/src/main/res/drawable/vector_9.xml
  app/src/main/res/drawable/vector_9dark.xml
Labels: enhancement

#143 fix: fix test build issues and conflict with changes
  app/src/test/java/com/london/tudee/data/mappers/CategoryMappersTest.kt
  app/src/test/java/com/london/tudee/data/mappers/TaskMapperTest.kt
  app/src/test/java/com/london/tudee/data/services/CategoriesServicesImplTest.kt
  app/src/test/java/com/london/tudee/presentation/screens/category/CategoriesViewModelTest.kt
  app/src/test/java/com/london/tudee/presentation/screens/home/HomeViewModelTest.kt
Labels: invalid
